language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
  #push to csci server
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/dir csci311e@otter.csci.viu.ca:public_html/
  on:
    branch: master
