name: scp files
on: [push]
jobs:

  run:
    name: Build
    runs-on: [self-hosted]
    steps:
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
          local: .
          remote: ~/public_html/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
